Detect all mahogany home repairs
Hydrox6/external-plugins pull request #100
Opened 2023-03-13 01:30 UTC by PeaceBear0

Previously it was missing IDs for Leela's mirror (40010) and Mariah's hat stand (40289). Instead, check for the names rather than the IDs since the same names are used for each house.

2023-03-13 04:44 UTC, Enriath requested changes
I would much prefer that IDs are used over strings, and given that you've mentioned only two, the change to support them would be incredibly minor, compared to replacing the entire system.

2023-03-13 04:44 UTC, Enriath commented on build.gradle
> +def runeLiteVersion = '1.9.12'
This doesn't need changing

2023-03-14 04:08 UTC, PeaceBear0 commented on build.gradle
> +def runeLiteVersion = '1.9.12'
Undid the change.

2023-03-14 04:09 UTC, PeaceBear0 commented
Switched back to using IDs, added a comment saying which item each ID applied to and added the 2 that were missing.

2023-03-16 02:37 UTC, merged